---
title: Expression Evaluation
---

Finally, we must discuss the equals (=) button. How, exactly, should this work? Admittedly, we could manually calculate the expression and return a result. However, Python provides the eval function that takes a string, evaluates it as an arithmetic expression, and returns a numeric result. Here are several examples:

``` python
eval("1+1")              # the returned result is 2
eval("5+(4-2)**5+6*2")   # the returned result is 49
```

Evaluating the expression on the display is now pretty simple! We just need to send the expression to Python's *eval* function to get a numeric result. Then, we can change the display, replacing it with a string version of the returned result. It looks something like this:

```python
expr = self.display["text"]
result = eval(expr)
self.display["text"] = str(result)
```

The first line stores the expression from the display to the variable expr, the second line evaluates the expression with Python's eval function, and the third line stores the result (as a string) back to the display. Of course, the three lines could be combined into a single statement; however, it is probably slightly less readable:

```python
self.display["text"] = str(eval(self.display["text"]))
```

Let's implement the evaluation portion by modifying the process method as follows:

``` python
# processes button presses
def process(self, button):
    # AC clears the display
    if (button == "AC"):
        # clear the display
        self.display["text"] = ""
    # = starts an evaluation of whatever is on the display
    elif (button == "="):
        # get the expression in the display
        expr = self.display["text"]
        # evaluate the expression
        result = eval(expr)
        # store the result to the display
        self.display["text"] = str(result)
    # otherwise, just tack on the appropriate operand/operator
    else:
    self.display["text"] += button
```

At this point, a valid arithmetic expression in the display will be properly evaluated and updated with the result. But what if the expression in the display is not valid? For example, what is the result of the expression <span style="color:red">4 + 5 *</span> (note the missing operand after the multiplication operator)? In fact, an error is outputted to the console (note that errors on different systems may differ slightly):

```
Exception in Tkinter callback
Traceback (most recent call last):
    File"/usr/local/Cellar/python3/3.6.1/Frameworks/Python.
        framework/Versions/3.6/lib/python3.6/tkinter/__init__.py",
        line 1699, in __call__
        return self.func(*args)
    File "TheReckoner-TEMPLATE9.py", line 153, in <lambda>
        button = Button(self, bg="white", image=img,borderwidth=0,
        highlightthickness=0, activebackground=
        "white",command=lambda: self.process("="))
    File "TheReckoner-TEMPLATE9.py", line 176, in process
        result = eval(expr)
    File "<string>", line 1
    4+5*
    ^
SyntaxError: unexpected EOF while parsing
```

Evidently, there was an unexpected EOF (end of file) while parsing the expression. Of course, this makes sense: the end of the expression was reached before a valid expression was provided. That is, the *eval* function expected more to the expression. To make the calculator more robust, we can detect such errors and provide an appropriate response to the user. This can be accomplished by using a **try-except** block (you should have seen this before!). The purpose of a **try-except** block is to encapsulate instructions that could cause an exception (something that alters the normal flow of a program) in a try block. If an exception occurs, it can be handled in the **except** block. More details about **try-except** will be covered later in the curriculum.

Let's handle any invalid expression evaluation by setting the calculator's display to the string ERROR so that the user is aware that an error occurred. This can be accomplished by modifying the process method as follows:

```python
# get the expression in the display
expr = self.display["text"]
# the evaluation may return an error!
try:
    # evaluate the expression
    result = eval(expr)
    # store the result to the display
    self.display["text"] = str(result)
# handle if an error occurs during evaluation
except:
    # note the error in the display
    self.display["text"] = "ERROR"
```

Note that the evaluation of the expression (into the variable result) and the subsequent modification of the display with the result is done in the **try** block. If this results in an error, the **except** block is executed, setting the contents of the display to the string ERROR.

Congratulations, you've made a simple calculator! Indeed, it's basic; however, there are many improvements that could be made:

• The length of the display supports approximately 12 characters; however, more characters could
be added to the display by the user. Doing so results in a cropped expression, which is probably
not desired. The display could be limited to 12 characters, ignoring any further input. Moreover,
the result of an expression could be larger than 12 characters. Perhaps such results could be
truncated.

• There is no easy way to erase the last character entered of an expression in the display. Adding a
back button to the calculator could allow this in case the user makes an error.

• Other useful operators could be added. For example: modulus (%), square root, logarithm (log),
natural logarithm (ln), factorial (!), sine, cosine, tangent, and constants such as pi and e. Take
look at the Google calculator (search for “calculator” on Google). Of course, Python's eval
function must support these (you'll have to try them out!).

• Most calculators clear any previous expression result if the user enters a new expression. For
example, suppose that the display has the result of an expression. If the user decides to enter a
different expression, the display must first be cleared. Currently, the user must do this manually
(by pressing the AC button). Perhaps the display could be automatically cleared of an expression
result if the user begins to enter a new expression.

• Similarly, perhaps the display could be cleared of an error if the user begins to enter a new
expression.

For completeness, here's the entire code (reduced in font size for readability):

```python
from tkinter import *

# the main GUI
class MainGUI(Frame):
    # the constructor
    def __init__(self, parent):
        Frame.__init__(self, parent, bg="white")
        parent.attributes("-fullscreen", True)
        self.setupGUI()
    # sets up the GUI
    def setupGUI(self):
        # https://www.fontsquirrel.com/fonts/tex-gyre-adventor)
        # on most Linux system, simply double-click the font files and install them
        # on the RPi, copy them to /usr/local/share/fonts (with
        # sudo): sudo cp tex*.otf /usr/local/share/fonts
        # then reboot

        # the display
        # right-align text in the display; and set its
        #  background to white, its height to 2 characters, and its font to 50 point TexGyreAdventor
        self.display = Label(self, text="", anchor=E,\
        bg="white", height=2, font=("TexGyreAdventor", 50))
        # put it in the top row, spanning across all four columns; and expand it on all four sides
        self.display.grid(row=0, column=0, columnspan=4,\
        sticky=E+W+N+S)

        # the button layout
        # ( ) AC **
        # 7 8 9 /
        # 4 5 6 *
        # 1 2 3 -
        # 0 . = +

        # configure the rows and columns of the Frame to adjust to the window
        # there are 6 rows (0 through 5)
        for row in range(6):
            Grid.rowconfigure(self, row, weight=1)
        # there are 4 columns (0 through 3)
        for col in range(4):
            Grid.columnconfigure(self, col, weight=1)

        # the first row
        # (
        # first, fetch and store the image
        # to work best on the RPi, images should be 115x115 pixels
        # otherwise, may need to add .subsample(n)
        img = PhotoImage(file="images/lpr.gif")
        # next, create the button (white background, no border,
        # no highlighting, no color when clicked)
        button = Button(self, bg="white", image=img, borderwidth=0, highlightthickness=0,\
        activebackground="white", command=lambda: self.process("("))
        # set the button's image
        button.image = img
        # put the button in its proper row and column
        button.grid(row=1, column=0, sticky=N+S+E+W)
        # the same is done for the rest of the buttons
        # )
        img = PhotoImage(file="images/rpr.gif")
        button = Button(self, bg="white", image=img, borderwidth=0, highlightthickness=0,\
        activebackground="white", command=lambda: self.process(")"))
        button.image = img
        button.grid(row=1, column=1, sticky=N+S+E+W)
        # AC
        img = PhotoImage(file="images/clr.gif")
        button = Button(self, bg="white", image=img, borderwidth=0, highlightthickness=0,\
        activebackground="white", command=lambda: self.process("AC"))
        button.image = img
        button.grid(row=1, column=2, sticky=N+S+E+W)
        # **
        img = PhotoImage(file="images/pow.gif")
        button = Button(self, bg="white", image=img, borderwidth=0, highlightthickness=0,\
        activebackground="white", command=lambda: self.process("**"))
        button.image = img
        button.grid(row=1, column=3, sticky=N+S+E+W)

        # the second row
        # 7
        img = PhotoImage(file="images/7.gif")
        button = Button(self, bg="white", image=img, borderwidth=0, highlightthickness=0,\
        activebackground="white", command=lambda: self.process("7"))
        button.image = img
        button.grid(row=2, column=0, sticky=N+S+E+W)
        # 8
        img = PhotoImage(file="images/8.gif")
        button = Button(self, bg="white", image=img, borderwidth=0, highlightthickness=0,\
        activebackground="white", command=lambda: self.process("8"))
        button.image = img
        button.grid(row=2, column=1, sticky=N+S+E+W)
        # 9
        img = PhotoImage(file="images/9.gif")
        button = Button(self, bg="white", image=img, borderwidth=0, highlightthickness=0,\
        activebackground="white", command=lambda: self.process("9"))
        button.image = img
        button.grid(row=2, column=2, sticky=N+S+E+W)
        # /
        img = PhotoImage(file="images/div.gif")
        button = Button(self, bg="white", image=img, borderwidth=0, highlightthickness=0,\
        activebackground="white", command=lambda: self.process("/"))
        button.image = img
        button.grid(row=2, column=3, sticky=N+S+E+W)

        # the third row
        # 4
        img = PhotoImage(file="images/4.gif")
        button = Button(self, bg="white", image=img, borderwidth=0, highlightthickness=0,\
        activebackground="white", command=lambda: self.process("4"))
        button.image = img
        button.grid(row=3, column=0, sticky=N+S+E+W)
        # 5
        img = PhotoImage(file="images/5.gif")
        button = Button(self, bg="white", image=img, borderwidth=0, highlightthickness=0,\
        activebackground="white", command=lambda: self.process("5"))
        button.image = img
        button.grid(row=3, column=1, sticky=N+S+E+W)
        # 6
        img = PhotoImage(file="images/6.gif")
        button = Button(self, bg="white", image=img, borderwidth=0, highlightthickness=0,\
        activebackground="white", command=lambda: self.process("6"))
        button.image = img
        button.grid(row=3, column=2, sticky=N+S+E+W)
        # *
        img = PhotoImage(file="images/mul.gif")
        button = Button(self, bg="white", image=img, borderwidth=0, highlightthickness=0,\
        activebackground="white", command=lambda: self.process("*"))
        button.image = img

        button.grid(row=3, column=3, sticky=N+S+E+W)

        # the fourth row
        # 1
        img = PhotoImage(file="images/1.gif")
        button = Button(self, bg="white", image=img, borderwidth=0, highlightthickness=0,\
        activebackground="white", command=lambda: self.process("1"))
        button.image = img
        button.grid(row=4, column=0, sticky=N+S+E+W)
        # 2
        img = PhotoImage(file="images/2.gif")
        button = Button(self, bg="white", image=img, borderwidth=0, highlightthickness=0,\
        activebackground="white", command=lambda: self.process("2"))
        button.image = img
        button.grid(row=4, column=1, sticky=N+S+E+W)
        # 3
        img = PhotoImage(file="images/3.gif")
        button = Button(self, bg="white", image=img, borderwidth=0, highlightthickness=0,\
        activebackground="white", command=lambda: self.process("3"))
        button.image = img
        button.grid(row=4, column=2, sticky=N+S+E+W)
        # -
        img = PhotoImage(file="images/sub.gif")
        button = Button(self, bg="white", image=img, borderwidth=0, highlightthickness=0,\
        activebackground="white", command=lambda: self.process("-"))
        button.image = img
        button.grid(row=4, column=3, sticky=N+S+E+W)

        # the fifth row
        # 0
        img = PhotoImage(file="images/0.gif")
        button = Button(self, bg="white", image=img, borderwidth=0, highlightthickness=0,\
        activebackground="white", command=lambda: self.process("0"))
        button.image = img
        button.grid(row=5, column=0, sticky=N+S+E+W)
        # .
        img = PhotoImage(file="images/dot.gif")
        button = Button(self, bg="white", image=img, borderwidth=0, highlightthickness=0,\
        activebackground="white", command=lambda: self.process("."))
        button.image = img
        button.grid(row=5, column=1, sticky=N+S+E+W)
        # =
        img = PhotoImage(file="images/eql.gif")
        button = Button(self, bg="white", image=img, borderwidth=0, highlightthickness=0,\
        activebackground="white", command=lambda: self.process("="))
        button.image = img
        button.grid(row=5, column=2, sticky=N+S+E+W)
        # +
        img = PhotoImage(file="images/add.gif")
        button = Button(self, bg="white", image=img, borderwidth=0, highlightthickness=0,\
        activebackground="white", command=lambda: self.process("+"))
        button.image = img
        button.grid(row=5, column=3, sticky=N+S+E+W)

        # pack the GUI
        self.pack(fill=BOTH, expand=1)

    # processes button presses
    def process(self, button):
    # AC clears the display
        if (button == "AC"):
            # clear the display
            self.display["text"] = ""
        # = starts an evaluation of whatever is on the display
        elif (button == "="):
            # get the expression in the display
            expr = self.display["text"]
            # the evaluation may return an error!
            try:
                # evaluate the expression
                result = eval(expr)
                # store the result to the display
                self.display["text"] = str(result)
            # handle if an error occurs during evaluation
            except:
                # note the error in the display
                self.display["text"] = "ERROR"
        # otherwise, just tack on the appropriate
        # operand/operator
        else:
            self.display["text"] += button

##############################
# the main part of the program
##############################
# create the window
window = Tk()
# set the window title
window.title("The Reckoner")
# generate the GUI
p = MainGUI(window)
# display the GUI and wait for user interaction
window.mainloop()
```
