## The hexadecimal number system
Base sixteen, or **hexadecimal**, uses sixteen symbols: “0” through “9” for the numbers zero through nine,
and “A” through “F” for the numbers ten through fifteen. The number sixteen is written as “10” in base 
sixteen, since after the symbol “F” is encountered, it is necessary to cycle back to the beginning of the 
sequence, “0.” When this occurs, the digit immediately to the left of the current digit (an understood 
“0”) is incremented to “1,” giving “10.” The following illustrates the base ten, base two, and base 
sixteen representations of the numbers zero through twenty. For readability, binary numbers have been 
padded to the left with zeros:

| Base 10 (decimal) | Base 2 (binary) | Base 16 (hexadecimal) |
|--|:--------|----------|
| 0 | 00000 | 0 |
| 1 | 00001 | 1 |
| 2 | 00010 | 2 |
| 3 | 00011 | 3 |
| 4 | 00100 | 4 |
| 5 | 00101 | 5 |
| 6 | 00110 | 6 |
| 7 | 00111 | 7 |
| 8 | 01000 | 8 |
| 9 | 01001 | 9 |
| 10 | 01010 | A |
| 11 | 01011 | B |
| 12 | 01100 | C |
| 13 | 01101 | D |
| 14 | 01110 | E |
| 15 | 01111 | F |
| 16 | 10000 | 10 |
| 17 | 10001 | 11 |
| 18 | 10010 | 12 |
| 19 | 10011 | 13 |
| 20 | 10100 | 14 |

In order to clearly distinguish which base a number-symbol is to be interpreted under, we generally 
write the base (two, ten, or sixteen) as a subscript immediately following the digits of the number.
Therefore, 11~2~ is three, 11~10~ is eleven, and 11~16~ is seventeen. It is standard operating procedure to omit 
the subscript base if the number is in base 10 (decimal). Repeating the above examples: 11~2~ is three, 11 
is eleven, and 11~16~ is seventeen.


