---
title: "Python Lists"
---

## List Basics
Although you should be familiar with Python lists, they are quite important and used often; therefore, we will go over it again. Generally, a Python  **sequence**  is composed of elements (typically related elements). Each element in a sequence is assigned an index (or position).  A sequence with  `n` elements has indexes `0` to `n–1`. Python has many built-in types of sequences; however, the most popular is called the **list**.

The list in Python is quite versatile. Recall that a list is declared using square brackets; for example:

```Python
grades = [94, 78, 100, 86]   
```

The statement above declares the list  `grades`  with four integers: 94, 78, 100, and 86. The list can be displayed in its entirety (e.g., with the statement  `print(grades)` ); however, we can access each element individually by its index (specified within brackets).  Accessing can mean to read a value in the list, or it can mean to change a value in the list; for example:  

```Python
print(grades[0])   # reading the value  at index 0 
grades[3] = 87     # setting the value at index 3   
grades[1] += 2     # adding 2 to the value at index 1
```

## Slicing

Recall that more than one value in a list can be accessed at a time. We can specify a range (or interval) of indexes in the format `[lower:upper+1]`  which means the interval $[lower, upper)$ (i.e., closed atlower and open at upper).  That is, the lower index in the range is inclusive but the upper is not.  For    
example: 

```Python
stuff[3:4]  # accesses index 3 (the same as stuff[3])   
stuff[0:5]  # accesses indexes 0 through 4   
stuff[-3]   # accesses the third index  from the right   
```

## Other Usages
Recall that various keywords and functions exist for us to modify or find information about a list. Here is a list of a few.

```Python
del grades[2]   # delete the item at index 2

len(grades)   # Returns the length of a list   

max(grades)   # Returns the item in the list with the maximum value   

min(grades)   # Returns the item in the list with the minimum value  
```

## List Methods
Lastly, recall that lists have various methods that can be used to operate on the list. Here are a few of them.

```Python
grades.append(item)           # Inserts item at the end of the list   

grades.count(item)            # Returns the number of times an item appears in the list   

grades.index(item)            # Returns the index of the first occurrence of item   

grades.insert(index, item)    # Inserts an item at the specified index in the list   

grades.remove(item)           # Removes the first occurrence of item from the list   

grades.reverse()              # Reverses the items in the list   

grades.sort()                 # Sorts a list   
```



